### PR TITLE
Order flags alphabetically

### PR DESCRIPTION
**Pull request by carmenquan**
Ordering flags by flag name, removing unused parameter in `FlagTreeStructure` constructor.

image

### CODE REVIEW

**Comment by yusinto** [comment]
Thanks for doing this @carmenquan ! I wonder though, should we perform the sort at the [network fetch level ](https://github.com/launchdarkly/ld-intellij/blob/38ebb140c40d3dc301e7011f55bfcf456f9eee9b/src/main/kotlin/com/launchdarkly/intellij/FlagStore.kt#L58)so all of the plugin uses the alphabetically sorted collection? In other words, are there instances in the plugin where we don't want flags to be alphabetically sorted?

**Review by yusinto — APPROVED** [review]
One curious question re where we should perform sorting, but otherwise lgtm.

**Comment by carmenquan** [comment]
that's a great point Yus, I'll move the logic over there so we can make sure we're consistent across the plugin to start

**Review by yusinto — APPROVED** [review]
Lgtm

**Pull request merged**
