### PR TITLE
move fields to advanced section

### PR DESCRIPTION
**Pull request by jazanne**
- [x] wait to add descriptions https://app.shortcut.com/launchdarkly/story/145174/copy-updates-for-the-preferences-panel

CleanShot 2022-03-10 at 17 46 05

CleanShot 2022-03-10 at 17 45 49

### CODE REVIEW

**Comment by yusinto** [comment]
Thanks for doing this. I think we're missing the time units for code refs refresh rate. Also, the "Enable Code References" checkbox looks a bit weird now that it's under Advanced. I'll defer to @darrinlin to comment since we don't have figma designs for this yet.

**Comment by jazanne** [comment]
> the "Enable Code References" checkbox looks a bit weird now that it's under Advanced

@darrinlin we could experiment with having **enable code references** and corresponding **refresh rate** in the same row, which might make it looks less weird. @InTheCloudDan what is the time unit for code refs refresh?

**Comment by InTheCloudDan** [comment]
@jazanne it's currently in `minutes`

**Comment by jazanne** [comment]
Here's another option:

Disabled
CleanShot 2022-03-10 at 10 07 35

Enabled
CleanShot 2022-03-10 at 10 07 44

Based on examples from JetBrains:
CleanShot 2022-03-10 at 10 08 34

**Review by yusinto — APPROVED** [review]

**Pull request merged**
